name: loserland
services:
    node_back:
        container_name: c_node_back
        image: veteastoll/node_back
        networks:
            - reseau
        ports:
            - ${PORT_BACK}:3000
        volumes:
            - .:/home/node/app
    node_front:
        container_name: c_node_front
        image: veteastoll/node_front
        networks:
            - reseau
        ports:
            - ${PORT_FRONT}:80
        volumes:
            - .:/home/node/app
    mariadb:
        container_name: c_mariadb
        image: mariadb
        networks:
            - reseau
        ports:
            - ${PORT_MARIADB}:3306
        environment:
            - MARIADB_ROOT_PASSWORD=${ROOT_PASSWORD_DB}
            - MARIADB_USER=${LOGIN_DB}
            - MARIADB_PASSWORD=${PASSWORD_DB}
            - MARIADB_DATABASE=info411
        volumes:
            - ./dbdata:/var/lib/mysql
            - ./sql:/docker-entrypoint-initdb.d
    phpmyadmin:
        container_name: c_phpmyadmin
        image: phpmyadmin
        networks:
            - reseau
        ports:
            - ${PORT_PMA}:80
        environment:
            - PMA_HOST=mariadb
networks:
    reseau:
        name: reseau