FROM node:23-alpine

WORKDIR /home/node/app

COPY . .

RUN cp ./backend/db_connect.js.docker ./backend/db_connect.js && \
    npm install --production

VOLUME ["/home/node/app"]

EXPOSE 3000

CMD ["node", "backend/server.js"]