FROM node:18-alpine

WORKDIR /home/node/app

RUN apk add --no-cache git && \
    git clone https://github.com/VeteaSTOLL/info411 . && \
    cp ./backend/db_connect.js.docker ./backend/db_connect.js && \
    npm install --production

EXPOSE 3000

CMD ["node", "backend/server.js"]