FROM node:18-alpine

WORKDIR /home/node/app

RUN apk add --no-cache git && \
    git clone https://github.com/VeteaSTOLL/info411 . && \
    npm install --production

EXPOSE 8080

CMD ["node", "app.js"]